export const API_KEYSEARCH = '&api_key=b6bbbb876524fb068f4abcc95fa67e9f';
export const API_KEY2 = '?api_key=340854c6d4e0cc3575399a4c61edf636';
export const FETCHING_MOVIES = 'FETCHING_MOVIES';
export const FETCHING_MOVIES_SUCCESS = 'FETCHING_MOVIES_SUCCESS';
export const FETCHING_MOVIES_FAILURE = 'FETCHING_MOVIES_FAILURE';
export const FETCHING_MOVIETRAILER = 'FETCHING_MOVIETRAILER';
export const FETCHING_MOVIETRAILER_SUCCESS = 'FETCHING_MOVIETRAILER_SUCCESS';
export const FETCHING_MOVIETRAILER_FAILURE = 'FETCHING_MOVIETRAILER_FAILURE';
export const FETCHING_CAST = 'FETCHING_CAST';
export const FETCHING_CAST_SUCCESS = 'FETCHING_CAST_SUCCESS';
export const FETCHING_CAST_FAILURE = 'FETCHING_CAST_FAILURE';
export const FETCHING_MOVIEBYID = 'FETCHING_MOVIEBYID';
export const FETCHING_MOVIEBYID_SUCCESS = 'FETCHING_MOVIEBYID_SUCCESS';
export const FETCHING_MOVIEBYID_FAILURE = 'FETCHING_MOVIEBYID_FAILURE';
export const FETCHING_SEARCH_MOVIE = 'FETCHING_SEARCH_MOVIE';
export const FETCHING_SEARCH_MOVIE_SUCCESS = 'FETCHING_SEARCH_MOVIE_SUCCESS';
export const FETCHING_SEARCH_MOVIE_FAILURE = 'FETCHING_SEARCH_MOVIE_FAILURE';
export const FETCHING_POPULAR_MOVIES = 'FETCHING_POPULAR_MOVIES';
export const FETCHING_POPULAR_MOVIES_SUCCESS = 'FETCHING_POPULAR_MOVIES_SUCCESS';
export const FETCHING_POPULAR_MOVIES_FAILURE = 'FETCHING_POPULAR_MOVIES_FAILURE';

export const FETCHING_GENRE = 'FETCHING_GENRE';
export const FETCHING_GENRE_SUCCESS = 'FETCHING_GENRE_SUCCESS';
export const FETCHING_GENRE_FAILURE = 'FETCHING_GENRE_FAILURE';

export const FETCHING_MOVIES_BY_GENRE = 'FETCHING_MOVIES_BY_GENRE';
export const FETCHING_MOVIES_BY_GENRE_SUCCESS = 'FETCHING_MOVIES_BY_GENRE_SUCCESS';
export const FETCHING_MOVIES_BY_GENRE_FAILURE = 'FETCHING_MOVIES_BY_GENRE_FAILURE';

export const IMG_LOGO_XS_SIZE = 'w45/';
export const IMG_LOGO_S_SIZE = 'w185/';
export const IMG_LOGO_M_SIZE = 'w300/';
export const IMG_LOGO_L_SIZE = 'w500/';
export const URL_LIST = 'https://api.themoviedb.org/3/discover/movie';
export const URL_SEARCH = 'https://api.themoviedb.org/3/search/movie?query=';
export const URL_DETAIL = 'https://api.themoviedb.org/3/movie/';
export const URL_PERSON = 'https://api.themoviedb.org/3/person/';
export const URL_GENRE = 'https://api.themoviedb.org/3/genre/'
export const URL_IMG = 'https://image.tmdb.org/t/p/';
export const URL_YOUTUBE = 'https://www.youtube.com/embed/';
export const URL_CAST = '/casts';
export const URL_VIDEO = '/videos';

export const UPDATE_ALLMOVIESBYGENRE = 'UPDATE_ALLMOVIESBYGENRE';
export const SEARCH = 'SEARCH';
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';

export const UPDATE_GENRE_SELECTION = 'UPDATE_GENRE_SELECTION';
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';

export const BROKEN_IMAGE = 'http://rlv.zcache.com/broken_internet_image_icon_poster-r0a8517b32a704c618ef72685782dc663_a3uq_8byvr_324.jpg';


export const FETCHING_MOVIES_BY_GENRES = 'FETCHING_MOVIES_BY_GENRES';
export const FETCHING_MOVIES_BY_GENRES_SUCCESS = 'FETCHING_MOVIES_BY_GENRES_SUCCESS';
export const FETCHING_MOVIES_BY_GENRES_FAILURE = 'FETCHING_MOVIES_BY_GENRES_FAILURE';